### ISSUE TITLE
Only pull mode

### ISSUE THREAD

**Issue by alejo9010** [Xian55/WowClassicGrindBot#133]
hi, im triying to create  a mode for my needs, i need it to pull only, i tried excluding the combat goal but its not working, after pulling it goes into a  NO PLAN state, and just keep walking forward, you think this is a bug ? it should get one of the goal in the list if no combat is selected

**Comment by Xian55** [comment]
There were issues with the introduced changes. Some/most of them should be fixed. 😓 

Try this one https://github.com/Xian55/WowClassicGrindBot/commit/42781b54c831e522f5822ab366998136362f0a43 and make sure the latest addon is installed and properly set up. 

Upon login to your character make sure to see this https://github.com/Xian55/WowClassicGrindBot/blob/42781b54c831e522f5822ab366998136362f0a43/Addons/DataToColor/DataToColor.toc#L5 version number!

**Comment by alejo9010** [comment]
i updated all the files now, but it seems like blacklist is having some bugs now, seems like when it gets a blacklisted target, it spams arrow key up/down, try it and let me know if u have the same results

**Comment by Xian55** [comment]
Just pushed a change https://github.com/Xian55/WowClassicGrindBot/commit/11bebb1c7320083ca11509796120f4609ffc758b which should be a remedy for the previously mentioned issue.

Let me know if it got any better

**Comment by alejo9010** [comment]
hi i did some testing, but still not working like it should if i remove the combat goal, i also tried skiping targets when their hp is not at 100%, but i end up at NO PLAN when it start to tapCleartarget...

**Comment by Xian55** [comment]
I mean its working correctly as intended, if you look at the logs you can see whats going on, and where the clear target happens.

> 2021-09-28 08:42:27.622 -05:00 [INF] PullTargetGoal: Entered combat after 0.0009ms
2021-09-28 08:42:27.630 -05:00 [INF] NO PLAN
2021-09-28 08:42:27.638 -05:00 [INF] Target Health: 71, max 71, dead False
2021-09-28 08:42:27.646 -05:00 [INF] Input: TapNearestTarget: GoapAgent[Tab] pressing for 50ms
2021-09-28 08:42:27.747 -05:00 [INF] Input: TapClearTarget: GoapAgent[Insert] pressing for 50ms
2021-09-28 08:42:27.830 -05:00 [INF] Input: TapStopAttack: [Delete] pressing for 50ms
2021-09-28 08:42:27.997 -05:00 [INF] PullTargetGoal: Entered combat after 0.0009ms
2021-09-28 08:42:28.004 -05:00 [INF] ---------------------------------

**Comment by alejo9010** [comment]
yeah, but once it hits the return in the pullgoal, why it wont go back to followroute? i have it set to clea target when mob hp < 100, but it just ends up at no plan.
instead, when it sees that the target is not at 100%, it stand in place, spamming clear target and no plan.

**Comment by Xian55** [comment]
If you check the code you will see the `CurrentGoal` is not being changed when it does not find a new plan. It keeps repeating the existing one.

https://github.com/Xian55/WowClassicGrindBot/blob/7339a7e9f44c1e62583c5adbb071fce4a7e4fee7/Core/GOAP/GoapAgent.cs#L69

**Comment by Xian55** [comment]
i've been updated how the `NO PLAN` state being handled. Check out latest https://github.com/Xian55/WowClassicGrindBot/commit/01235df8981b9330dab13ee429daab790f0d382f There are no more 
> Input: TapNearestTarget: GoapAgent[Tab]

so maybe it would be easier to achieve your plans!

**Comment by alejo9010** [comment]
im getting same results, no plan, ill try blacklisting the target after the pull see if that works.
