### ISSUE TITLE
If bot can't reach targeted mob it does not behave as intended

### ISSUE THREAD

**Issue by TeamMonolith** [Xian55/WowClassicGrindBot#421]
### Description

When the bot is trying to reach an enemy and can't reach it, the bot notices and the and console keeps saying "seems stuck! Clear target." (see image). But instead, it just keeps spamming " I " which is bound to "Interact With Target" thus not clearing the target and causing the bot to be stuck and trying to reach the enemy forever.

according to the setup guide, the "Insert" key is meant for the "/cleartarget" macro.

### Addon Version

1.7.19

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

1. have the bot target an enemy it can't reach (for example on a steep hill or behind a wall)
2. bot will try reaching it forever

### Last Good Version

I don't know

### Screenshots

![image](https://user-images.githubusercontent.com/91420203/189554228-1e5e4840-9a10-4dc3-b97c-0b02ff59af0f.png)

**Comment by Xian55** [comment]
Hello there,

Have you created the Bindpad addon key for `/cleartarget` ?

**Comment by TeamMonolith** [comment]
yes, like I said it should be pressing "Insert" and not "I" :)

**Comment by Xian55** [comment]
can you upload your class profile json here?

**Comment by Xian55** [comment]
On the other hand please upload the log file where this issue happened.

**Comment by TeamMonolith** [comment]
Here you go, I did modify it a bit for my needs, but I hope I broke nohing :)
[class.zip](https://github.com/Xian55/WowClassicGrindBot/files/9543778/class.zip)

**Comment by TeamMonolith** [comment]
[out20220912.log](https://github.com/Xian55/WowClassicGrindBot/files/9543783/out20220912.log)
2022-09-12 01:36:38.843 +02:00 time it happens, I was around this time so I cleared target myself after a few minutes

**Comment by Xian55** [comment]
This logfile is not valid, as missing the initialization part. Please upload the full, unedited log file.

the beginning starts in
out20220911.log

**Comment by TeamMonolith** [comment]
I did not edit it, but it produced weirdly many logs.
![image](https://user-images.githubusercontent.com/91420203/189555072-0f65cfd3-0b4b-4147-8f83-f0a3012f33cb.png)

**Comment by TeamMonolith** [comment]
[BlazorServer.zip](https://github.com/Xian55/WowClassicGrindBot/files/9543799/BlazorServer.zip)
All logs I got, nothing edited

**Comment by TeamMonolith** [comment]
can't find any log called "out20220911.log"
Edit: 
While trying to provide the logs I accidentally ran the "run.bat" causing 2 instances of it to run. I think that is the reason for all the small logs. So it is not related to the issue.

**Comment by Xian55** [comment]
There's nothing weird about the small 1kb log files as they unable to start due the BlazorServer already running.
```
2022-09-12 02:12:57.009 +02:00 [INF] Startup()
2022-09-12 02:12:57.131 +02:00 [INF] Using AddonDataProviderGDI
2022-09-12 02:12:57.170 +02:00 [INF] Program.Main(): Failed to bind to address http://0.0.0.0:5000: address already in use.
2022-09-12 02:12:57.171 +02:00 [INF] 
2022-09-12 02:13:00.185 +02:00 [INF] Program.Main(): Starting blazor server
``` 

After an exception, BlazorServer attempts to restart itself, thats how you most likely got that many start up attempts, which reflect the log file file numbering.

**Comment by TeamMonolith** [comment]
Yea I noticed, I accidentally started another instance while looking for logs :D

**Comment by Xian55** [comment]
Are you sure you have set the Clear target in Bindpad addon?

What happens, when you 
* stop the Blazor server
* target anything even yourself
* press `Insert` button ?

**Comment by TeamMonolith** [comment]
it works, it does remove the target

**Comment by TeamMonolith** [comment]
while it was happening I opened my chat window and it typed "IIIIIIIIIIIIIIIIIIIIIIII" thus I assume it just spams "I" instead of  "Insert".

**Comment by TeamMonolith** [comment]
oh nice, you are quick :D

Will I need to recompile for this to take effect?

**Comment by Xian55** [comment]
i've pushed #422  `dev` branch. Could you check `dev` branch latest?

be sure to pull `dev` branch first

Yes you have to recompile. with command
```sh
dotnet build --configuration Release --arch x86
```

**Comment by TeamMonolith** [comment]
It doesn't happen too often, but I will try forcing it and report back :)

**Comment by Xian55** [comment]
No need to force it, take your time, no need to rush.

**Comment by TeamMonolith** [comment]
it behaves differently but still isn't using "insert" to stop targeting.

For some reason, it isn't producing any .log files, so I am just gonna paste the full console content unless you know why I get no logs.
[consolePaste.txt](https://github.com/Xian55/WowClassicGrindBot/files/9543875/consolePaste.txt)

![image](https://user-images.githubusercontent.com/91420203/189557115-0eb6011e-8d70-4811-9f1f-8f844148e31f.png)
^no logs

**Comment by Xian55** [comment]
Could you edit the following line `Game\Input\WowProcessInput.cs`

```cs
private const bool LogInput = false;
```
to
```cs
private const bool LogInput = true;
```

Delete all of the exsiting log files, under BlazorServer folder, be sure to recompile.

After the next run should be able to see every single input keydown actions.

**Comment by Xian55** [comment]
That's not a good sign at all, check the `BlazorServer/bin` folder.

**Comment by TeamMonolith** [comment]
I was a dumbo, I made a backup of my files and downloaded the new dev branch to a new folder, and used copied over my run.bat with the backup path in it. Meaning it still ran the old version. That's why there where no new logs, the logs happened in the backup folder. So the problem was actually fixed by your change😅

**Comment by Xian55** [comment]
I would recommend to use [git](https://git-scm.com/download/win)

With a few commands  to learn, you can stay up to date.

To `checkout` the project, one time 
```sh
git clone https://github.com/Xian55/WowClassicGrindBot.git
cd WowClassicGrindBot
```

once there's an update you can `pull`
```sh
git pull
```

**Comment by Xian55** [comment]
Here's a pretty quick guide on how to use [git commands](http://rogerdudler.github.io/git-guide/)
